install.packages(c("tidyverse", "readxl", "gridExtra", "extrafont", "hrbrthemes", "sysfonts", "showtext", "haven", "brms", "rcartocolor", "here", 
                   "texreg", "knitr", "ggmcmc", "performance", "ggforce"))

library(tidyverse)
library(gridExtra)
library(extrafont)
library(hrbrthemes)
library(sysfonts)
library(showtext)
library(readxl)
library(brms)
library(haven)
library(rcartocolor)
library(here)
library(texreg)
library(knitr)
library(ggmcmc)
library(performance)
library(ggforce)

